# taps
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"

# python 
brew "pyenv"
brew "poetry"

# neovim
brew "bob" 

# fonts 
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"

# desktop apps
cask "rectangle"
cask "iterm2"
cask "slack"
cask "visual-studio-code"
cask "zoom"
cask "scroll-reverser"

# others
brew "cmake"
brew "fd"
brew "node"

