# taps
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/services"

# fonts 
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"

# neovim
brew "bob" 

# python 
brew "pyenv"
brew "poetry"
brew "sphinx-doc"

# terminal
cask "iterm2"
brew "zsh"
brew "tmux"
brew "fd"
brew "git"
brew "curl"
brew "wget"
brew "cmake"
brew "powerlevel10k"
brew "neofetch"

# desktop apps
cask "rectangle"
cask "slack"
cask "visual-studio-code"
cask "zoom"
cask "scroll-reverser"

# others
brew "node"
