## aliases
source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/functions.zsh
source ~/.config/zsh/settings.zsh

# ohmyzsh
source ~/.config/ohmyzsh/ohmyzsh.zsh

## p10k
source $HOMEBREW_PREFIX/share/powerlevel10k/powerlevel10k.zsh-theme
source ~/.config/p10k/p10k.zsh

