# Q pre block. Keep at the top of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.pre.zsh"
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

## aliases
source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/functions.zsh
source ~/.config/zsh/settings.zsh

# ohmyzsh
source ~/.config/ohmyzsh/ohmyzsh.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source ~/.config/p10k/p10k.zsh

# show neofetch 
# neofetch

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/arthur/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/arthur/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/arthur/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/arthur/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# Q post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/amazon-q/shell/zshrc.post.zsh"
