## p10k
source ~/.config/p10k/p10k.zsh

## aliases
source ~/.config/zsh/env.zsh
source ~/.config/zsh/aliases.zsh
source ~/.config/zsh/functions.zsh
source ~/.config/zsh/settings.zsh

# ohmyzsh
source ~/.config/ohmyzsh/ohmyzsh.zsh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
source ~/.config/p10k/p10k.zsh

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/arthur/Downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/Users/arthur/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/arthur/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/Users/arthur/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# CodeWhisperer post block. Keep at the bottom of this file.
[[ -f "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.post.zsh" ]] && builtin source "${HOME}/Library/Application Support/codewhisperer/shell/zshrc.post.zsh"
