# SOPS configuration file
# This file configures how SOPS encrypts/decrypts secrets

# Define key groups for encryption
keys:
  - &host_key age1l5caupkg9lfue0fah4y8g2zxdszh3x86hsg9e4auamxptmgm3ywsy6w2ht

# Creation rules define which keys can decrypt which files
creation_rules:
  - path_regex: secrets\.yaml$
    key_groups:
    - age:
      - *host_key

  # Encrypt only values, leave keys in plaintext for readability
  - path_regex: .*
    encrypted_regex: '^(data|stringData)$'
